INSERT INTO rh_cargafamiliar
				SET
					CodSecuencia = '2',
					CodPersona = '000430',
					Parentesco = 'MA',
					ApellidosCarga = 'FLORES',
					NombresCarga = 'ANA MARGARITA',
					DireccionFam = 'AV BOLIVAR CASA Nº 12 SECTOR VIENTO COLAO',
					FechaNacimiento = '1956-07-11',
					TipoDocumento = '01',
					Ndocumento = '4368013',
					Telefono = '',
					Celular = '04140365080',
					Sexo = 'F',
					GrupoSanguineo = '',
					Afiliado = 'S',
					CodGradoInstruccion = '',
					Estado = 'A',
					MotivoBaja = '',
					FechaBaja = '',
					TipoEducacion = '',
					CodCentroEstudio = '',
					FlagTrabaja = 'N',
					Empresa = '',
					DireccionEmpresa = '',
					TiempoServicio = '0',
					SueldoMensual = '0',
					Comentarios = '',
					FlagEstudia = 'N',
					EstadoCivil = '01',
					FlagDiscapacidad = 'N',
					Foto='000430.jpg',
					UltimoUsuario = 'RDEPABLOS',
					UltimaFecha = NOW();

